/* 幸福人生觉察卡 — single source of truth for card data.
   Shared by the client deck (Layer 1) and the report API (Layer 2). */

export const CHAPTERS = {
  1: { cn: "防护模式", en: "Protection Patterns", color: "#3c4a72", tint: "#e7e9f2" },
  2: { cn: "人生课题", en: "Life Lessons", color: "#3f7a4c", tint: "#e5f0e6" },
  3: { cn: "潜意识剧本", en: "Subconscious Scripts", color: "#2c2c33", tint: "#e8e6ea" },
  4: { cn: "转化成长", en: "Transformation", color: "#b5842b", tint: "#f5ecd6" },
};

export const CARDS = [
  { n: 1, ch: 1, cn: "恐惧", en: "FEAR", icon: "🐺", grad: ["#1f2a30", "#41544c"],
    text_cn: "我害怕的，是眼前的现实，还是我想象的威胁？", text_en: "What am I afraid of — the reality before me, or a threat created by my imagination?",
    affect_cn: "恐惧会放大想象中的威胁，让你在还没发生的事上提前消耗能量，悄悄缩小你的世界。", affect_en: "Fear magnifies imagined threats, draining energy on things that haven't happened and quietly shrinking your world.",
    practice_cn: "问自己：此刻我是真的不安全，还是只是「想象」不安全？", practice_en: "Ask: am I truly unsafe right now, or only imagining it?" },
  { n: 2, ch: 1, cn: "攻击", en: "ATTACK", icon: "💥", grad: ["#7a2418", "#c0512e"],
    text_cn: "当我受伤时，我是否只能用攻击来保护自己？", text_en: "When I feel hurt, is attacking the only way I know to protect myself?",
    affect_cn: "用攻击保护自己，往往推开了你最想靠近的人，也让伤痛不断循环。", affect_en: "Attacking to protect yourself often pushes away the people you most want close, and keeps the hurt cycling.",
    practice_cn: "在反击之前，先说出：「我其实受伤了。」", practice_en: "Before striking back, name it: \u201CI'm actually hurt.\u201D" },
  { n: 3, ch: 1, cn: "批判", en: "JUDGMENT", icon: "🗯️", grad: ["#6b6459", "#a89a86"],
    text_cn: "我对自己的苛刻，是否比别人更甚？", text_en: "Am I harsher toward myself than anyone else is?",
    affect_cn: "对自己的苛刻会内化成一个严厉的声音，让每一次尝试都伴随批评。", affect_en: "Harsh self-judgment becomes an inner critic that shadows every attempt with criticism.",
    practice_cn: "用对好朋友说话的语气，对自己说一句。", practice_en: "Speak to yourself in the tone you'd use with a good friend." },
  { n: 4, ch: 1, cn: "羞愧", en: "SHAME", icon: "🫙", grad: ["#3b3b46", "#7d7a6a"],
    text_cn: "我是否把「羞愧」当作了督促自己前进的方式？", text_en: "Have I been using shame as a way to push and motivate myself?",
    affect_cn: "把羞愧当动力，会让成长建立在「我不够好」之上——越努力，越空。", affect_en: "Using shame as fuel builds growth on \u201CI'm not enough\u201D — the harder you push, the emptier it feels.",
    practice_cn: "试着用「我想变好」代替「我很糟糕」。", practice_en: "Replace \u201CI'm bad\u201D with \u201CI want to grow.\u201D" },
  { n: 5, ch: 1, cn: "讨好", en: "PEOPLE-PLEASING", icon: "🌟", grad: ["#6a5a48", "#d8b892"],
    text_cn: "我是否为了被爱，而失去了真正的自己？", text_en: "Have I lost my authentic self in my desire to be loved?",
    affect_cn: "为被爱而讨好，会让你慢慢弄丢自己真实的需要和声音。", affect_en: "Pleasing others to be loved slowly costs you your real needs and your own voice.",
    practice_cn: "今天，诚实说出一个你真正想要的东西。", practice_en: "Today, honestly say one thing you actually want." },
  { n: 6, ch: 1, cn: "罪恶感", en: "GUILT", icon: "🪨", grad: ["#5a4636", "#c98a5a"],
    text_cn: "我是否背负着不属于我的责任，而无法轻松前行？", text_en: "Am I carrying responsibilities that don't belong to me, making it hard to move forward with ease?",
    affect_cn: "背负不属于你的责任，会让你替别人的人生买单，无法轻松前行。", affect_en: "Carrying responsibilities that aren't yours makes you pay for others' lives and weighs down every step.",
    practice_cn: "分清楚：这份责任，真的是我的吗？", practice_en: "Sort it out: is this burden actually mine?" },
  { n: 7, ch: 1, cn: "期待", en: "EXPECTATION", icon: "🪧", grad: ["#7a8a6a", "#cdd6b0"],
    text_cn: "我是否活在别人的期待里，而忘了自己的渴望？", text_en: "Am I living in others' expectations while forgetting what I truly desire?",
    affect_cn: "活在别人的期待里，你会离自己的渴望越来越远，成就也难有满足。", affect_en: "Living inside others' expectations pulls you from your own desires, and achievement rarely satisfies.",
    practice_cn: "问：这是「我的期待」，还是「他们的期待」？", practice_en: "Ask: is this my expectation, or theirs?" },
  { n: 8, ch: 1, cn: "逃避", en: "AVOIDANCE", icon: "🌫️", grad: ["#4a4a44", "#c8c2a8"],
    text_cn: "我在逃避的，是痛苦，还是成长的机会？", text_en: "Am I avoiding pain, or avoiding an opportunity to grow?",
    affect_cn: "逃避痛苦时，你也常常逃开了成长的入口，问题只是被推到未来。", affect_en: "Avoiding pain often means avoiding the doorway to growth; the problem just waits for you later.",
    practice_cn: "选一件小小的、你一直在拖的事，今天面对它。", practice_en: "Pick one small thing you've been avoiding, and face it today." },
  { n: 9, ch: 1, cn: "冻结", en: "FREEZE", icon: "🧊", grad: ["#3a5a7a", "#a8cfe0"],
    text_cn: "在面对压力时，我是否选择了停止，而不是面对？", text_en: "When facing pressure, do I shut down instead of facing it?",
    affect_cn: "压力下选择停住，能暂时保护你，但也让你卡在原地，动弹不得。", affect_en: "Freezing under pressure protects you for a moment, but leaves you stuck and unable to move.",
    practice_cn: "做一个最小的动作——一次深呼吸、一步——就能开始解冻。", practice_en: "Take the smallest action — one breath, one step — to begin thawing." },
  { n: 10, ch: 1, cn: "控制", en: "CONTROL", icon: "♟️", grad: ["#3a3a4a", "#7a7488"],
    text_cn: "我试图控制的一切，是否让我失去了真正的自由？", text_en: "Has all I try to control cost me my true freedom?",
    affect_cn: "想控制一切，反而被「必须掌控」困住，失去了流动和真正的自由。", affect_en: "Trying to control everything traps you in the need to control, costing you flow and true freedom.",
    practice_cn: "选一件事，练习「放手，让它发生」。", practice_en: "Choose one thing and practice letting it happen." },

  { n: 11, ch: 2, cn: "归属", en: "BELONGING", icon: "🏡", grad: ["#8ab05a", "#f0e2b0"],
    text_cn: "我是否感到，我属于某个地方或某些人？", text_en: "Do I feel like I belong somewhere or to someone?",
    affect_cn: "当你感到不属于任何地方，会时时向外寻找容身之所，难以安定。", affect_en: "When you feel you belong nowhere, you keep searching outside for a place to rest, never quite settling.",
    practice_cn: "先在自己心里，为自己留一个家。", practice_en: "First, make a home for yourself inside yourself." },
  { n: 12, ch: 2, cn: "关系", en: "RELATIONSHIP", icon: "🐕", grad: ["#6aa04a", "#cfe6a0"],
    text_cn: "我是否愿意建立真实的连接，而不只是表面的关系？", text_en: "Am I willing to build genuine connections, not just surface-level ones?",
    affect_cn: "只停留在表面的关系，会让你身边有人，却依然孤独。", affect_en: "Staying at surface-level relationships leaves you surrounded by people yet still lonely.",
    practice_cn: "对一个人，多说一句真心话。", practice_en: "Share one more honest sentence with someone." },
  { n: 13, ch: 2, cn: "爱", en: "LOVE", icon: "💗", grad: ["#8ac0e0", "#f5c8d8"],
    text_cn: "我是否愿意去爱，也允许自己被爱？", text_en: "Am I willing to love and also allow myself to be loved?",
    affect_cn: "若只愿给爱、不敢被爱，爱会变得单向而疲惫。", affect_en: "Giving love but not allowing yourself to receive it makes love one-way and exhausting.",
    practice_cn: "今天，允许自己接受一份好意。", practice_en: "Today, let yourself receive one kindness." },
  { n: 14, ch: 2, cn: "真实", en: "AUTHENTICITY", icon: "🪞", grad: ["#5a8a4a", "#c8e0a0"],
    text_cn: "我是否有勇气，活出真正的自己？", text_en: "Do I have the courage to be my true self?",
    affect_cn: "藏起真实的自己，会让别人喜欢的，其实是一个面具。", affect_en: "Hiding your true self means what people like is really a mask.",
    practice_cn: "露出一点点真实的你，看看会发生什么。", practice_en: "Show a little of the real you and see what happens." },
  { n: 15, ch: 2, cn: "勇气", en: "COURAGE", icon: "⛰️", grad: ["#6a9ac0", "#cfe0e8"],
    text_cn: "我是否愿意面对恐惧，迈出下一步？", text_en: "Am I willing to face my fears and take the next step?",
    affect_cn: "不敢面对恐惧，你的世界会停在恐惧划定的边界里。", affect_en: "Not facing your fears keeps your world inside the borders fear has drawn.",
    practice_cn: "迈出那让你有点害怕的一小步。", practice_en: "Take the small step that scares you a little." },
  { n: 16, ch: 2, cn: "信任", en: "TRUST", icon: "⛵", grad: ["#c99a5a", "#f0d8a8"],
    text_cn: "我是否愿意相信自己，也相信生命的安排？", text_en: "Am I willing to trust myself and trust life's plan?",
    affect_cn: "不信任自己与生命，你会想控制每个细节，活得紧绷。", affect_en: "Without trust in yourself and life, you try to control every detail and live tensed up.",
    practice_cn: "对一件事说：「我相信它会安排好。」", practice_en: "Tell one situation: \u201CI trust this will work out.\u201D" },
  { n: 17, ch: 2, cn: "边界", en: "BOUNDARIES", icon: "🚧", grad: ["#6a9a4a", "#d0e6a8"],
    text_cn: "我是否愿意划出界限，保护自己的能量？", text_en: "Am I willing to set boundaries and protect my energy?",
    affect_cn: "没有界限，你的能量会不断流失，被他人的需要填满。", affect_en: "Without boundaries, your energy leaks away, filled up by everyone else's needs.",
    practice_cn: "温柔而坚定地说一次「不」。", practice_en: "Say \u201Cno\u201D once, gently and firmly." },
  { n: 18, ch: 2, cn: "时间", en: "TIME", icon: "⏳", grad: ["#7a9a3a", "#d8e0a0"],
    text_cn: "我是否愿意善用时间，活在当下？", text_en: "Am I willing to use my time wisely and live in the present?",
    affect_cn: "总活在过去或未来，会让你错过当下正在发生的生命。", affect_en: "Living in the past or future makes you miss the life happening now.",
    practice_cn: "花三分钟，只专注在此刻正在做的事。", practice_en: "Spend three minutes fully present with what you're doing." },
  { n: 19, ch: 2, cn: "选择", en: "CHOICE", icon: "🔀", grad: ["#7ab0d0", "#dce8c0"],
    text_cn: "我是否愿意为自己选择，而不被他人或过去决定？", text_en: "Am I willing to choose for myself rather than be decided by others or the past?",
    affect_cn: "让他人或过去替你决定，你会觉得人生不是自己的。", affect_en: "Letting others or the past decide leaves you feeling your life isn't your own.",
    practice_cn: "今天，为自己做一个小小的主动选择。", practice_en: "Make one small choice for yourself today." },
  { n: 20, ch: 2, cn: "意义", en: "PURPOSE", icon: "🌅", grad: ["#c9a0c0", "#f0d8b8"],
    text_cn: "我是否愿意寻找生命的意义，并活出属于自己的价值？", text_en: "Am I willing to discover life's meaning and live my own value?",
    affect_cn: "找不到属于自己的意义，努力也会显得空洞。", affect_en: "Without your own sense of meaning, even effort can feel hollow.",
    practice_cn: "写下一件「让你觉得值得」的小事。", practice_en: "Write down one thing that feels worth it to you." },

  { n: 21, ch: 3, cn: "无价值感", en: "WORTHLESSNESS", icon: "💔", grad: ["#2a2a30", "#7a7a82"],
    text_cn: "我是否总觉得自己不够好，不值得被爱和重视？", text_en: "Do I always feel I'm not good enough, not worthy of love and attention?",
    affect_cn: "「我不够好」的剧本会让你自动低估自己，拒绝本该属于你的爱与机会。", affect_en: "The \u201CI'm not good enough\u201D script makes you underrate yourself and turn away love and chances that are yours.",
    practice_cn: "对自己说：「我本来就值得。」", practice_en: "Tell yourself: \u201CI am worthy as I am.\u201D" },
  { n: 22, ch: 3, cn: "流浪者", en: "WANDERER", icon: "🧭", grad: ["#3a3a5a", "#c9a878"],
    text_cn: "我是否总觉得自己没有家，在寻找一个可以属于的地方？", text_en: "Do I always feel I have no home, searching for a place to belong?",
    affect_cn: "「我没有家」的剧本让你不断迁徙寻找，却始终无法安放自己。", affect_en: "The \u201CI have no home\u201D script keeps you wandering and searching, never able to settle.",
    practice_cn: "问：我能不能，先成为自己的家？", practice_en: "Ask: can I become my own home first?" },
  { n: 23, ch: 3, cn: "心魔", en: "INNER DEMON", icon: "👹", grad: ["#1a1a1e", "#4a4048"],
    text_cn: "我是否被内心的恐惧、怀疑或愤怒，不断困扰和消耗？", text_en: "Am I constantly troubled and drained by fear, doubt or anger inside me?",
    affect_cn: "恐惧、怀疑、愤怒的内在声音，会在暗处悄悄消耗你的力量。", affect_en: "The inner voices of fear, doubt and anger quietly drain your strength from the shadows.",
    practice_cn: "给那个声音命名，你就不再被它掌控。", practice_en: "Name the voice, and it loses its grip on you." },
  { n: 24, ch: 3, cn: "无意义感", en: "MEANINGLESSNESS", icon: "❓", grad: ["#4a4640", "#b0a890"],
    text_cn: "我是否常常感到空虚，找不到生活的意义和方向？", text_en: "Do I often feel empty and lost, without meaning or direction?",
    affect_cn: "「一切都没意义」的剧本会抽走你的方向感，让日子变得灰白。", affect_en: "The \u201Cnothing matters\u201D script drains your sense of direction and greys out your days.",
    practice_cn: "找一件微小却真实的美好，专注它。", practice_en: "Find one small, real, good thing and rest your attention there." },
  { n: 25, ch: 3, cn: "完美幻想", en: "PERFECTION ILLUSION", icon: "💫", grad: ["#8a8478", "#d8d0c0"],
    text_cn: "我是否活用「完美」来要求自己，永远无法真正满足？", text_en: "Do I use \u201Cperfection\u201D to demand of myself, never truly satisfied?",
    affect_cn: "用「完美」要求自己，你永远差一点，永远无法真正满足。", affect_en: "Demanding \u201Cperfect\u201D of yourself, you're always a bit short and never truly satisfied.",
    practice_cn: "让一件事，停在「足够好」。", practice_en: "Let one thing rest at \u201Cgood enough.\u201D" },
  { n: 26, ch: 3, cn: "孤独旅人", en: "LONELY TRAVELER", icon: "🏮", grad: ["#2a2a4a", "#8a7ab0"],
    text_cn: "我是否习惯独自承担一切，不敢依靠别人？", text_en: "Am I used to carrying everything alone, afraid to rely on others?",
    affect_cn: "「只能靠自己」的剧本让你独自扛下一切，不敢求助。", affect_en: "The \u201CI can only rely on myself\u201D script makes you carry everything alone, afraid to ask.",
    practice_cn: "向一个人说出：「我需要帮忙。」", practice_en: "Tell one person: \u201CI need help.\u201D" },
  { n: 27, ch: 3, cn: "危险世界", en: "DANGEROUS WORLD", icon: "⚡", grad: ["#22222a", "#5a5060"],
    text_cn: "我是否觉得这个世界充满威胁，总是需要保护自己？", text_en: "Do I feel the world is full of threats, always needing to protect myself?",
    affect_cn: "「世界很危险」的剧本让你时刻戒备，很难真正放松与信任。", affect_en: "The \u201Cthe world is dangerous\u201D script keeps you on guard, unable to truly relax or trust.",
    practice_cn: "找一个此刻你确实安全的证据。", practice_en: "Find one piece of evidence that you are safe right now." },
  { n: 28, ch: 3, cn: "匮乏之井", en: "SCARCITY", icon: "🪣", grad: ["#4a4038", "#a89878"],
    text_cn: "我是否总觉得不够，无论拥有多少都无法满足？", text_en: "Do I always feel \u201Cnot enough\u201D, no matter how much I have?",
    affect_cn: "「永远不够」的剧本让你无论拥有多少，都焦虑匮乏。", affect_en: "The \u201Cnever enough\u201D script keeps you anxious and lacking no matter how much you have.",
    practice_cn: "写下三件你已经拥有的丰盛。", practice_en: "Write three things you already have in abundance." },
  { n: 29, ch: 3, cn: "命运枷锁", en: "FATE CHAINS", icon: "⛓️", grad: ["#2a2e34", "#6a6870"],
    text_cn: "我是否认为命运早已注定，无法改变自己的生活？", text_en: "Do I believe my fate is fixed and I can't change my life?",
    affect_cn: "「命运已注定」的剧本让你放弃改变，把力量交给了过去。", affect_en: "The \u201Cfate is fixed\u201D script makes you give up on change and hand your power to the past.",
    practice_cn: "选一件你今天就能改变的小事。", practice_en: "Choose one small thing you can change today." },
  { n: 30, ch: 3, cn: "掌控者", en: "CONTROLLER", icon: "🪆", grad: ["#2e2a34", "#6a6070"],
    text_cn: "我是否试图掌控一切，以获得安全感？", text_en: "Do I try to control everything to feel safe?",
    affect_cn: "用掌控换安全感，会让你越抓越紧，也越来越累。", affect_en: "Trading control for safety makes you grip tighter and grow more tired.",
    practice_cn: "松开一件事，让别人或生命来接手。", practice_en: "Loosen your grip on one thing and let others, or life, take it." },

  { n: 31, ch: 4, cn: "觉察", en: "AWARENESS", icon: "☀️", grad: ["#d0b060", "#f5e8b8"],
    text_cn: "我看见自己，也看见生命的美好。", text_en: "I see myself, and I see the beauty of life.",
    affect_cn: "当你看见自己，你就有了选择的空间，也看见了生命的美好。", affect_en: "When you see yourself, you gain room to choose — and you begin to see the beauty of life.",
    practice_cn: "此刻，只是安静地看着自己的感受，不评判。", practice_en: "Right now, simply watch your own feelings, without judging." },
  { n: 32, ch: 4, cn: "接纳", en: "ACCEPTANCE", icon: "💛", grad: ["#c9a850", "#f0dca0"],
    text_cn: "我接纳自己的一切，温柔地拥抱真实的自己。", text_en: "I accept all of me, and embrace my true self with kindness.",
    affect_cn: "接纳真实的自己，内在的战争就停下来，你会更完整。", affect_en: "Accepting your true self ends the inner war and makes you more whole.",
    practice_cn: "对一个你不喜欢的自己的部分说：「我接纳你。」", practice_en: "Tell a part of you you dislike: \u201CI accept you.\u201D" },
  { n: 33, ch: 4, cn: "自由", en: "FREEDOM", icon: "🪁", grad: ["#5ab0e0", "#e0f0d8"],
    text_cn: "我选择属于自己的天空，自在地做自己。", text_en: "I choose my own sky, and freely be myself.",
    affect_cn: "选择属于自己的天空，你会活得更自在、更像自己。", affect_en: "Choosing your own sky lets you live freer and more like yourself.",
    practice_cn: "做一件「只因为我想」的事。", practice_en: "Do one thing just because you want to." },
  { n: 34, ch: 4, cn: "灵感", en: "INSPIRATION", icon: "💡", grad: ["#c9a860", "#f5e4b0"],
    text_cn: "我敞开心灵，灵感自然流动，指引我前行。", text_en: "I open my heart, and inspiration flows, guiding me forward.",
    affect_cn: "敞开心灵，灵感会自然流动，为你指出前行的方向。", affect_en: "With an open heart, inspiration flows naturally and points your way forward.",
    practice_cn: "留白十分钟，什么都不做，让念头自己来。", practice_en: "Leave ten empty minutes and let ideas come to you." },
  { n: 35, ch: 4, cn: "顺流", en: "FLOW", icon: "🌊", grad: ["#4aa0d0", "#dce8d0"],
    text_cn: "我信任生命的节奏，顺势而为，轻松前行。", text_en: "I trust the flow of life, and move forward with ease.",
    affect_cn: "信任生命的节奏，你会少一些对抗，多一些轻松。", affect_en: "Trusting life's rhythm brings less resistance and more ease.",
    practice_cn: "顺着今天的节奏走，不强求。", practice_en: "Move with today's rhythm instead of forcing it." },
  { n: 36, ch: 4, cn: "真爱", en: "TRUE LOVE", icon: "💞", grad: ["#d88aa0", "#f5d8c8"],
    text_cn: "我给予爱，也感受爱；我值得被爱，也懂得去爱。", text_en: "I give and feel love; I am worthy of love, and I know how to love.",
    affect_cn: "当你既给爱也收爱，爱会在你与世界之间流动。", affect_en: "When you both give and receive love, it flows between you and the world.",
    practice_cn: "对一个人表达一次真诚的爱。", practice_en: "Express genuine love to one person." },
  { n: 37, ch: 4, cn: "创造", en: "CREATION", icon: "🎨", grad: ["#6ab0d0", "#f0e0b0"],
    text_cn: "我用创造表达自己，让想象力成为现实的力量。", text_en: "I express myself through creation, turning imagination into reality.",
    affect_cn: "用创造表达自己，你的想象力会成为改变现实的力量。", affect_en: "Expressing yourself through creation turns imagination into a force that shapes reality.",
    practice_cn: "做一件小小的创造：写、画、或做点什么。", practice_en: "Make one small thing: write, draw, or build something." },
  { n: 38, ch: 4, cn: "天赋", en: "TALENT", icon: "🎸", grad: ["#c9a040", "#f5e0a0"],
    text_cn: "我发现自己的天赋，并勇敢地分享给世界。", text_en: "I discover my talents, and bravely share them with the world.",
    affect_cn: "发现并分享天赋，你会活出属于自己的光。", affect_en: "Discovering and sharing your gifts lets you live your own light.",
    practice_cn: "说出一个你擅长的事，并大方承认它。", practice_en: "Name one thing you're good at, and own it." },
  { n: 39, ch: 4, cn: "成就", en: "ACHIEVEMENT", icon: "🏆", grad: ["#d09850", "#f5d8a0"],
    text_cn: "我一步一步努力，实现目标，创造价值。", text_en: "I take one step at a time, achieve my goals, and create value.",
    affect_cn: "一步一步地努力，价值会在积累中真实地长出来。", affect_en: "Step by step, real value grows through what you build.",
    practice_cn: "为一个目标，完成今天的一小步。", practice_en: "Take one small step toward a goal today." },
  { n: 40, ch: 4, cn: "丰盛", en: "ABUNDANCE", icon: "🌈", grad: ["#d0a850", "#f0e0b0"],
    text_cn: "我打开自己，迎接丰盛，生命以无限的方式回馈我。", text_en: "I open myself to abundance, and life returns to me in endless ways.",
    affect_cn: "当你打开自己，生命会以无限的方式回馈你。", affect_en: "When you open yourself, life returns to you in endless ways.",
    practice_cn: "心怀感恩地接受今天到来的一切。", practice_en: "Receive whatever comes today with gratitude." },
];

export const byNum = Object.fromEntries(CARDS.map((c) => [c.n, c]));

/* Three-card position combinations from the guidebook */
export const SPREAD3 = [
  { name: "过去 · 现在 · 未来", en: "Past / Present / Future", pos: [["过去", "Past"], ["现在", "Present"], ["未来", "Future"]] },
  { name: "现况 · 行动 · 结果", en: "Situation / Action / Result", pos: [["现况", "Situation"], ["行动", "Action"], ["结果", "Result"]] },
  { name: "思维 · 身体 · 心灵", en: "Mind / Body / Spirit", pos: [["思维", "Mind"], ["身体", "Body"], ["心灵", "Spirit"]] },
  { name: "优势 · 弱点 · 建议", en: "Strength / Weakness / Advice", pos: [["优势", "Strength"], ["弱点", "Weakness"], ["建议", "Advice"]] },
  { name: "选项一 · 二 · 三", en: "Option 1 / 2 / 3", pos: [["选项一", "Option 1"], ["选项二", "Option 2"], ["选项三", "Option 3"]] },
  { name: "头脑 · 内心 · 灵魂", en: "Head / Heart / Soul", pos: [["头脑", "Head"], ["内心", "Heart"], ["灵魂", "Soul"]] },
  { name: "愿景 · 挑战 · 指引", en: "Vision / Challenge / Guidance", pos: [["愿景", "Vision"], ["挑战", "Challenge"], ["指引", "Guidance"]] },
  { name: "物质 · 情感 · 灵性", en: "Material / Emotional / Spiritual", pos: [["物质层面", "Material"], ["情感层面", "Emotional"], ["灵性层面", "Spiritual"]] },
  { name: "情境 · 障碍 · 心灵指引", en: "Situation / Obstacle / Guidance", pos: [["情境", "Situation"], ["障碍", "Obstacle"], ["心灵指引", "Guidance"]] },
  { name: "你 · 对方 · 关系", en: "You / Other / Relationship", pos: [["你", "You"], ["对方", "The Other"], ["关系", "Relationship"]] },
];

/* Inner Child four-card spread (guidebook order 1–4) */
export const INNER_CHILD = [
  ["需求 / 渴望", "Need / Desire", "你的内在小孩的需求或渴望", "What your inner child needs or longs for."],
  ["阻碍", "Obstacle", "阻碍你满足这些需求的因素", "What prevents these needs from being met."],
  ["行动", "Action", "为了克服阻碍，可以采取的行动", "An action that can help you move through the obstacle."],
  ["结果", "Outcome", "当这些需求获得满足后的结果", "What may become possible when these needs are met."],
];
